### ISSUE TITLE
Scroll bar on mobile has a white background on dark mode

### ISSUE THREAD

**Issue by Cody-W-Tucker** [sanity-io/next-sanity#1002]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

The scroll bar on mobile has a white background in dark mode.

It appears that the scheme is hard coded to light, this seems to cause the scroll bar to have a white background 

https://github.com/sanity-io/next-sanity/blob/be75214cfb66d54d92c7f0a760566e85187f52ab/src/studio/NextStudioLayout.tsx#L15

**To Reproduce**

1. Go to 'Studio in dark mode mobile'
2. Find something that overflows
3. See error

**Expected behavior**

The scroll bar should have no background or darker color.

**Screenshots**
![www codywtucker com_studio_structure](https://github.com/sanity-io/next-sanity/assets/37312240/d4785404-a348-48c1-b56c-b15bb370b04c)

**Which versions of Sanity are you using?**

Run `sanity versions` in the terminal and copy-paste the result here.
Sanity Studio version 3.28.0

**What operating system are you using?**
Linux 6.7.1

**Which versions of Node.js / npm are you running?**

Run `npm -v && node -v` in the terminal and copy-paste the result here.
10.2.4
v20.11.0

**Additional context**

**Security issue?**

Any security issues should be submitted directly to [security@sanity.io](mailto:security@sanity.io). In order to determine whether you are dealing with a security issue, ask yourself these two questions:

- Can I access something that's not mine, or something I shouldn't have access to?
- Can I disable something for other people? If the answer to either of those two questions are "yes", then you're probably dealing with a security issue. Note that even if you answer "no" to both questions, you may still be dealing with a security issue, so if you're unsure, just email us at [security@sanity.io](mailto:security@sanity.io.

**Comment by stipsan** [comment]
Could you give [v8](https://github.com/sanity-io/next-sanity/releases/tag/v8.0.0) a try?
