### ISSUE TITLE
Content Translation Support

### ISSUE THREAD

**Issue by tarifalhasan** [sanity-io/next-sanity#1009]
I would like to request a feature that enables the translation of content within the Sanity Studio. The goal is to make it easier for users to manage and present content in multiple languages.

Use Case
As an international user, I need the ability to manage content translations for my website in a seamless way. This feature would be particularly beneficial for projects that require content in multiple languages.

**Comment by stipsan** [comment]
Closing as you didn't fill out the template: https://github.com/sanity-io/next-sanity/issues/new?assignees=&labels=&projects=&template=feature_request.md&title=
