### ISSUE TITLE
TypeError createClient is not a function

### ISSUE THREAD

**Issue by paoyangt** [sanity-io/next-sanity#1012]
### Description
When I run `yarn dev` or `yarn build` and load any of my pages, I encounter the following error:

```
src/utils/sanity/lib/client.ts (5:35) @ eval
⨯ TypeError: (0 , next_sanity__WEBPACK_IMPORTED_MODULE_1__.createClient) is not a function
at eval (./src/utils/sanity/lib/client.ts:9:73)
```

This error prevents my app from building. It seems like the `createClient` method from `next-sanity` is not being recognized as a function.

### Steps to Reproduce
1. Run `yarn dev` or `yarn build` .
2. Load any page in the browser.

### Environment
- Node.js version: v18.17.1
- NPM version: 9.6.7
- `package.json` dependencies:
  ```
  {
    "dependencies": {
     "@headlessui/react": "^1.7.17",
    "@portabletext/react": "^3.0.11",
    "@sanity/client": "^6.12.4",
    "@sanity/demo": "1.0.2",
    "@sanity/icons": "^2.8",
    "@sanity/image-url": "^1.0.2",
    "@sanity/types": "^3.25",
    "@sanity/ui": "^2.0",
    "@sanity/vision": "^3.19.1",
    "@types/node": "^20.10.4",
    "@types/react": "^18.2.42",
    "@types/react-dom": "^18.2.17",
    "aos": "^3.0.0-beta.6",
    "contentlayer": "^0.3.2",
    "date-fns": "^2.30.0",
    "next": "^14.1",
    "next-contentlayer": "^0.3.4",
    "next-sanity": "8.0.0",
    "react": "^18.2",
    "react-dom": "18.2.0",
    "sanity": "^3.25",
    "styled-components": "^6.0",
    "typescript": "^5.3.3"
    }
  }


### Additional Context
Here is the snippet from src/utils/sanity/lib/client.ts where the error occurs:
```
import { createClient } from 'next-sanity';
...
export const client = createClient({
  apiVersion,
  dataset,
  projectId,
});
```

**Comment by stipsan** [comment]
Can you create a github repository that demonstrates the problem?
It would also be helpful to see the contents of your next.config.js file.

**Comment by paoyangt** [comment]
I'll need some time to prepare the github repository but in the meantime, here's my next.config.js file

const { withContentlayer } = require("next-contentlayer");

```
/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    domains: ["cdn.sanity.io"],
  },
};

module.exports = withContentlayer(nextConfig);

```

**Comment by stipsan** [comment]
Ah ok, thanks for reporting back 😄
