### ISSUE TITLE
Please allow for GraphQL query strings in createPreviewSubscriptionHook

### ISSUE THREAD

**Issue by XanderJL** [sanity-io/next-sanity#11]
Please correct me if I'm wrong, but I'd really love to not have to rewrite all of my queries in groq to allow for live previews of blog posts.

I'd love to just do something like:
```jsx
const postQuery = `
    query($slug: String!) {
      allPost(where: { slug: { current: { eq: $slug } } }) {
        _id
        title
        publishDate
        content
        slug {
          current
        }
      }
    }
 `

const {data: post} = usePreviewSubscription(postQuery, {
    params: {slug: data.post.slug},
    initialData: data,
    enabled: preview,
  })
```

**Comment by rexxars** [comment]
The Sanity GraphQL API doesn't support subscriptions currently, so this isn't trivial to implement, unfortunately. We could perhaps re-run the queries when something changes, but that could quickly lead to a large number of queries...
