### ISSUE TITLE
`apiVersion` missing from `ClientConfig` type

### ISSUE THREAD

**Issue by alexbchr** [sanity-io/next-sanity#13]
The `ClientConfig` interface for configuring the `picosanity` client is missing the `apiVersion` field, as documented in [Sanity Changelog](https://www.sanity.io/changelog#change-ec40c9f6-193d-48a8-bb55-8c4e05a93516).

This makes Typescript not compiling if defining the configuration as:

```ts
const config: ClientConfig = {
  // ... Config Fields
}
```

**Comment by rexxars** [comment]
Thanks, solved in #12 / v0.1.12
