### ISSUE TITLE
Usage with Next.js 13 ./app

### ISSUE THREAD

**Issue by alvarlagerlof** [sanity-io/next-sanity#137]
Hi, currently trying to integrate the Sanity Studio inside my site with `<NextStudio ... `. My project is using the new` ./app` directory and `"sanity": "3.0.0-rc.0"` + `"next-sanity": "1.0.8",`.

Currently getting this error.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/14835120/200127382-58d44104-562e-4dc0-84b3-ebee58fe544c.png">

I can of course install styled-components as a dependency, and that appears to let it attempt to render.
<img width="500" alt="image" src="https://user-images.githubusercontent.com/14835120/200127476-451be42f-2d5f-4814-8d20-043596bf0e66.png">

But that breaks all of my other pages in `./app`.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/14835120/200127483-7dc8b715-6faf-494e-8d5c-18546d7d977d.png">

My branch testing this is here: https://github.com/alvarlagerlof/portfolio/pull/610

**Comment by steven-tey** [comment]
Might need to add `sanity` and `next-sanity` in `next.config.js`?

https://beta.nextjs.org/docs/api-reference/next.config.js#servercomponentsexternalpackages

**Comment by alvarlagerlof** [comment]
> Might need to add `sanity` and `next-sanity` in `next.config.js`?
> 
> [beta.nextjs.org/docs/api-reference/next.config.js#servercomponentsexternalpackages](https://beta.nextjs.org/docs/api-reference/next.config.js#servercomponentsexternalpackages)

That worked better, but for now it seems I am blocked by lack of a `code-input` plugin on v3.

**Comment by stipsan** [comment]
You should be able to use `code-input` on v3 using:
```bash
npm install --save-exact @sanity/code-input@studio-v3
```

https://github.com/sanity-io/code-input#usage

**Comment by alvarlagerlof** [comment]
Nevermind, I still can't use both parts without styled-components.

**Comment by stipsan** [comment]
@alvarlagerlof could you push the changes @steven-tey suggested to https://github.com/alvarlagerlof/portfolio/pull/610 and I can give it a look?

**Comment by alvarlagerlof** [comment]
Yes! It's pushed now to [this](https://github.com/alvarlagerlof/portfolio/pull/610). Current state is the studio doesn't render without installing styled-components and the rest breaks when I do so.

**Comment by stipsan** [comment]
Thanks, I'll give it a go and use your branch as base @alvarlagerlof 🙌

**Comment by stipsan** [comment]
Hi @alvarlagerlof, we just released [v3](https://github.com/sanity-io/next-sanity/releases/tag/v3.0.0) which supports [Next 13 ./app for Studio embeds](https://github.com/sanity-io/next-sanity#next-13-appstudio) 🎉

**Comment by alvarlagerlof** [comment]
> Hi @alvarlagerlof, we just released [v3](https://github.com/sanity-io/next-sanity/releases/tag/v3.0.0) which supports [Next 13 ./app for Studio embeds](https://github.com/sanity-io/next-sanity#next-13-appstudio) tada

Cool. I am still blocked it seems because @sanity/code-input and @sanity/portable-text-editor both require server components. The code editor also hasn't been updated for "use client".

**Comment by stipsan** [comment]
It's not necessary to mark those dependencies as `use client`.

Refer to https://github.com/sanity-io/nextjs-blog-cms-sanity-v3/tree/main/app/studio/%5B%5B...index%5D%5D

You still need to [install](https://github.com/sanity-io/nextjs-blog-cms-sanity-v3/blob/57bf125fdeb3f10fc9088c2b0a11afd6986ef914/package.json#LL32C12-L32C12) the `styled-components` dependency, but you [don't need to setup SSR](https://beta.nextjs.org/docs/styling/css-in-js#styled-components) for it.

**Comment by alvarlagerlof** [comment]
I did follow that, and it fixed the css, but the code input still tried to run client things.

**Comment by stipsan** [comment]
Here you go @alvarlagerlof https://github.com/alvarlagerlof/portfolio/pull/646

**Comment by beamercola** [comment]
I'm having a similar issue are we sure this is fixed?

<img width="759" alt="Screen Shot 2022-12-16 at 2 29 20 PM" src="https://user-images.githubusercontent.com/8060/208199443-f577162b-a478-4870-a700-72b01baca938.png">

**Comment by alvarlagerlof** [comment]
> I'm having a similar issue are we sure this is fixed?
> 
> <img alt="Screen Shot 2022-12-16 at 2 29 20 PM" width="759" src="https://user-images.githubusercontent.com/8060/208199443-f577162b-a478-4870-a700-72b01baca938.png">

Just install styled-components as an extra dependency and this will go away. They haven't included it in their package yet.

**Comment by beamercola** [comment]
@alvarlagerlof I should have noted - i installed `"styled-components": "^5.3.6"`

**Comment by stipsan** [comment]
`styled-components` is now a peer dependency: https://github.com/sanity-io/next-sanity#next-sanitystudio-peer-dependencies
