### ISSUE TITLE
Api-versioning

### ISSUE THREAD

**Issue by winsvold** [sanity-io/next-sanity#14]
I doesn't look like it's possible to turn on [api-verisoning](https://www.sanity.io/docs/api-versioning) for the client, would love support for that :)

Especially I would like to turn it on for the createPreviewSubscriptionHook, but when I pass apiVersion  to the createPreviewSubscriptionHook it still seems to be using the v1-endpoint.

```
export const usePreviewSubscription = createPreviewSubscriptionHook({
  dataset: "production",
  projectId: "abc123",
  apiVersion: 'X'
});
```

From network-tab I can see it still using the v1-endpoint, don't know if there is a smarter way to see what version the client is using.

![image](https://user-images.githubusercontent.com/29202094/114503313-62cd1180-9c2d-11eb-8bd2-d18a077c208c.png)

https://sanity-io-land.slack.com/archives/C013NG0UF0B/p1618038372004900

**Comment by hdoro** [comment]
@borispoehland can you share the configuration you're using?

You should be able to use `apiVersion`: "YYYY-MM-DD"` as specified [in the docs](https://github.com/sanity-io/next-sanity#usage), but if you can't I'm glad to assist with debugging :)

**Comment by gtwebsite** [comment]
i did have same problem, but fixed when changing from
`*[_type == "page"] | order(_updatedAt desc) | [0]` to
`*[_type == "page"] | order(_updatedAt desc)[0]`

If you have similar problem, check your query string, some part could be outdated

**Comment by stipsan** [comment]
Closing as it seems resolved, but feel free to re-open if it's still a problem :)
