### ISSUE TITLE
Upgrading to Next 13.0.3 breaks usage of client in RSC.

### ISSUE THREAD

**Issue by Gawdfrey** [sanity-io/next-sanity#154]
## Description
I upgraded to Next 13.0.3 today and using the sanity client now does not work in RSC as the error presents that the component is using hooks. Everything works when using Next version 13.0.2. Next sanity version is latest, v1.0.9
![image](https://user-images.githubusercontent.com/46612252/201472749-06040367-ea32-4c75-b0da-cf9cb09a3536.png)

I was under the impression based on examples that using the client in RSC would be impossible, please correct me if I am wrong :)

This bug is introduced by Next 13.0.3 so it might be better to report this there, please let me know what is most appropriate.

## Temp fix
Downgrade to Next 13.0.2

## Steps to reproduce
1. Clone the following repository: https://github.com/Gawdfrey/next-sanity-13.0.3-issues
2. Add a .env.local file with NEXT_PUBLIC_SANITY_PROJECT_ID and NEXT_PUBLIC_SANITY_DATASET variables.
3. Run the project with pnpm run dev
4. See the error
5. Downgrade to Next 13.0.2 to see the example working fine.

**Comment by stipsan** [comment]
We've just released [`v2.0.0`](https://github.com/sanity-io/next-sanity/releases/tag/v2.0.0) which moves preview utils to `next-sanity/preview`, so you should be able to `import {createClient, groq} from 'next-sanity'` without needing to add `'use client'` 🙌
