### ISSUE TITLE
[Visual Editing] `draftMode().isEnabled` inside `sanityFetch()` breaks on build

### ISSUE THREAD

**Issue by mitchuman** [sanity-io/next-sanity#1598]
If you find a security vulnerability, do NOT open an issue. Email [security@sanity.io](mailto:security@sanity.io) instead.

**Describe the bug**

The [`draftMode().isEnabled` inside the `sanityFetch()`](https://github.com/sanity-io/next-sanity/blob/da7e53164762df75f20fc8dc7360043ccffddf1f/apps/mvp/app/sanity.fetch.ts#L20) declaration causes `npm run build` (works on `npm run dev`) to fail with the following error:

```sh
Error: `draftMode` was called outside a request scope. Read more: https://nextjs.org/docs/messages/next-dynamic-api-wrong-context
```

**To Reproduce**

**Expected behavior**

**Screenshots**

Full error:

```sh
> next build

  ▲ Next.js 14.2.3
  - Environments: .env.local

   Creating an optimized production build ...
 ✓ Compiled successfully
 ✓ Linting and checking validity of types    
   Collecting page data  ..Error: `draftMode` was called outside a request scope. Read more: https://nextjs.org/docs/messages/next-dynamic-api-wrong-context
    at getExpectedRequestStore (/next/node_modules/next/dist/client/components/request-async-storage.external.js:28:11)
    at p (/next/.next/server/chunks/615.js:1:1915)
    at i (/next/.next/server/chunks/483.js:19:861)
    at Object.f [as generateStaticParams] (/next/.next/server/app/[slug]/page.js:1:7012)
    at buildParams (/next/node_modules/next/dist/build/utils.js:1026:58)
    at buildParams (/next/node_modules/next/dist/build/utils.js:1020:28)
    at /next/node_modules/next/dist/build/utils.js:1043:39
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Object.wrap (/next/node_modules/next/dist/server/async-storage/static-generation-async-storage-wrapper.js:49:24)
    at buildAppStaticPaths (/next/node_modules/next/dist/build/utils.js:981:85)

> Build error occurred
Error: Failed to collect page data for /[slug]
    at /next/node_modules/next/dist/build/utils.js:1268:15 {
  type: 'Error'
}
```

**Which versions of Sanity are you using?**

```
@sanity/cli (global)        3.38.0 (latest: 3.45.0)
@sanity/image-url            1.0.2 (up to date)
@sanity/preview-url-secret  1.6.17 (up to date)
```

**What operating system are you using?**

macOS Sonoma 14.5

**Which versions of Node.js / npm are you running?**

```
9.5.0
v18.15.0
```

**Additional context**

I have a similar setup [found here](https://github.com/nuotsu/sanitypress/blob/main/next/src/lib/sanity/fetch.ts#L17-L18).
Differences:
- `"next": "^14.2.3"`
- `fetch.ts` resides under `/lib` not `/app`
- no `import 'server-only`
However, these did not make a difference in the error output.

**Security issue?**

**Comment by stipsan** [comment]
The `sanityFetch` pattern isn't meant to be used inside `generateStaticParams` API as it's not needed in this context:
- `perspective` should always be `published`.
- `stega` should always be `false`.
- there's no need to set `fetch.next` or `fetch.cache` options as it's used within the static build for ISR. Setting `fetch.next.revalidate` makes sense for React Server Components that behave differently depending on wether Draft Mode is enabled or not.

Instead we recommend using a typical `client.fetch` call inside `generateStaticParams` :)

**Comment by mitchuman** [comment]
This resolved it! TYSM 🙌
