### ISSUE TITLE
Dynamic Code Evaluation (e. g. 'eval', 'new Function', 'WebAssembly.compile') not allowed in Edge Runtime 

### ISSUE THREAD

**Issue by codeBelt** [sanity-io/next-sanity#1823]
**Describe the bug**

`"next-sanity": "9.5.0"` works fine but `9.6.0` and the latest `9.7.0` causes this issue.

In Vercel deployments I am seeing the error message:
`Dynamic Code Evaluation (e. g. 'eval', 'new Function', 'WebAssembly.compile') not allowed in Edge Runtime`.

<img width="1244" alt="Screenshot 2024-10-23 at 12 19 29 PM" src="https://github.com/user-attachments/assets/b7bee70a-ffc7-48c9-926b-16ed0977e050">

**To Reproduce**

Not sure of the steps. Only can tell you it started in `"next-sanity": "9.6.0",`.

**Which versions of Sanity are you using?**

@sanity/cli (global)  3.56.0 (latest: 3.62.0)
@sanity/image-url      1.0.2 (up to date)
@sanity/ui            2.8.10 (up to date)
@sanity/vision        3.62.0 (up to date)
sanity                3.62.0 (up to date)

**What operating system are you using?**

macOS Sonoma

**Which versions of Node.js / npm are you running?**

10.5.0
v21.7.2

**Comment by stipsan** [comment]
Is this in pages router or app router?

**Comment by codeBelt** [comment]
> Is this in pages router or app router?

app router

**Comment by stipsan** [comment]
@codeBelt could you let me know if https://github.com/sanity-io/next-sanity/releases/tag/next-sanity-v9.8.2 fixes it for you?
