### ISSUE TITLE
Document that usePreviewSubscription live preview has 3000 document dataset limit

### ISSUE THREAD

**Issue by stephenhmarsh** [sanity-io/next-sanity#183]
We wasted a lot of time setting up live preview only to find out that it needs to stream the entire dataset to the client and because of that there's a default 3000 document limit.  You should say that up front in the guides and docs. It's not a great developer experience to find that out the hard way.  Imagine, too, folks who do this for their whole codebase from the start only to find out it stops working when they hit 3000?

We would not have bothered experimenting with live preview at all if we knew this feature needed to stream the _entire_ dataset.

**Comment by stipsan** [comment]
Hi @stephenhmarsh, first off I understand the frustration.
For others joining this thread, [this is the documentation](https://github.com/sanity-io/next-sanity/tree/v1.0.9#limits) we've had in the past.

I want you to know that we're actively investing in live previews by telling you about what we've released recently and we're planning on doing in the future.

In [`next-sanity@v1.1`](https://github.com/sanity-io/next-sanity/releases/tag/v1.1.0) [we released `includeTypes`](https://github.com/sanity-io/next-sanity/tree/v1.1.0#usage:~:text=local%20groq%2Dstore.-,includeTypes,-%3A%20%5B%27page) to help limit the size of the dataset by excluding the document types you're not using in your previews.

In [`v2`](https://github.com/sanity-io/next-sanity/releases/tag/v2.0.0) we launched a big rewrite where `next-sanity` is now using [`@sanity/preview-kit`](https://github.com/sanity-io/preview-kit#usage) internally.
With this rewrite we're making an effort to better [surface the current limitations and how to work around them](https://github.com/sanity-io/next-sanity#limits).
This effort is also part of [how we document our new starters](https://github.com/sanity-io/nextjs-blog-cms-sanity-v3/blob/8953518cccdd0498e743618724e5c8071df8098f/lib/sanity.preview.ts#L18-L32).

To reiterate, our short term focus is to better document the current limitations and all the tools you have at your disposal to tweak the live preview experience.

The long term goal is to eliminate `@sanity/groq-store`, exporting your dataset locally and the `documentLimit` and `includeTypes` APIs completely. Building a live preview experience should be as simple updating your call to:
```diff
import {use} from 'react'
import {createClient} from 'next-sanity'
const client = createClient({
  projectId,
  dataset,
  apiVersion,
+ overlayDrafts: true,
})
export default function ReactComponent() {
  const data = use(client.fetch(
    query, params, 
+   {live: true}
  ))
}
```

Hope this helps @stephenhmarsh, and I want to thank you for letting us know 🙇

**Comment by stephenhmarsh** [comment]
Great to know, thank you.  Specifically the page that I wish had this info is: `https://www.sanity.io/guides/nextjs-live-preview`

**Comment by stipsan** [comment]
Thanks 😌 Until we've updated that guide to our updated tooling and best practices I recommend using this starter as a reference implementation of preview mode: https://github.com/sanity-io/nextjs-blog-cms-sanity-v3/tree/main

It has all the bells and whistles like:
- [Custom token auth](https://github.com/sanity-io/next-sanity#custom-token-auth)
- [Uses auto-generated secrets stored in your dataset](https://github.com/sanity-io/nextjs-blog-cms-sanity-v3/blob/main/plugins/productionUrl/utils.ts) to protect `/api/preview`, a much more secure method than hardcoding URL secrets like in the [referenced guide](https://www.sanity.io/guides/nextjs-live-preview).
- It is built on Next 13 and [Sanity Studio v3](https://www.sanity.io/studio-v3).

And feel free to reach out with any questions :relaxed:

**Comment by stephenhmarsh** [comment]
Oh wow, that's really helpful thank you.  Yeah, you can imagine I was a bit 🤨 when I saw an env named "SECRET" that was _not so secret_ -- I even thought about rolling my own thing that just hashed the doc `_id` against a key in both apps but I like the new example solution just fine.

**Comment by stipsan** [comment]
Haha yeah, the "🤨" is perfectly understandable 🙈  There are some historical reasons for this, for example, the `productionUrl` API in Studio v2 is sync so you can't just do an `await getSecret()`.

We're really excited to build on the new APIs in Studio v3 and ship better tooling.
For example [check out how we're doing preview mode in Remix ✨](https://github.com/SimeonGriggs/remix-sanity-studio-v3)
We'll talk more about what we have in store on the [Sanity Product Day™](https://www.sanity.io/productday) 🙌

**Comment by stipsan** [comment]
We're now documenting the limit in the readme: https://github.com/sanity-io/next-sanity#limits :relaxed:
