### ISSUE TITLE
defineLive can only be used in React Server Components error

### ISSUE THREAD

**Issue by luigifgp** [sanity-io/next-sanity#1871]
I'm trying to implement the new Live Content API and in our app we have a component provider that builds the website content, most of them are server component, a few of them fetch their own data using the `sanityFetch` but,  we have a couple of these components that have nested client components or they are fully client component. 
These client component cases breaks the whole application with an error (**_defineLive can only be used in React Server Components_**), however these are not using the `sanityFetch` api. 

This error is throw only on dev (local), on builds deployment seems to work fine.

1. Setup Live content API on your project: (SanityLive, sanityFetch ..)
2. Create nested client component within server component
3. run the project on development (local) 

**Screenshots**

![image](https://github.com/user-attachments/assets/096e1b02-74c9-4de3-80f4-c1b8a52c9471)

**Which versions of Sanity are you using?**

@sanity/cli (global)  3.54.0 (latest: 3.62.3)
@sanity/icons          3.4.0 (up to date)
@sanity/image-url      1.0.2 (latest: 1.1.0)
@sanity/overlays      2.3.59 (up to date)
@sanity/preview-kit    5.1.2 (latest: 5.1.11)
@sanity/react-loader  1.10.7 (latest: 1.10.14)
@sanity/table          1.1.2 (up to date)
@sanity/types         3.60.0 (latest: 3.62.3)
@sanity/ui             2.8.9 (latest: 2.8.18)
@sanity/util          3.60.0 (latest: 3.62.3)
@sanity/vision        3.60.0 (latest: 3.62.3)
sanity                3.62.2 (latest: 3.62.3)

"next-sanity": "^9.8.8",
"next": "^14.2.15",

node version: 22.6.0
pnpm version: 9.7.1

**What operating system are you using?**

Linux - Ubuntu

**Comment by stipsan** [comment]
Seems like one of your client components end up causing `defineLive` to be imported and called.

Could you try adding 
```
import 'server-only'
```
at the top of your `src/app/sanity.live.ts`? It should help with tracing down where the import is happening.
The gist of this is that even if a component is most of the time a server component, if it's imported by a client component then it can't import a file that calls `defineLive`.
There are good reasons why we don't allow this pattern, for example you might end up `@sanity/client` being bundled with your client components even though it's only used by server components and should remain on the server bundle only.

**Comment by luigifgp** [comment]
Thank you!! yes, that helped a lot, I was able to track the problem.

We were having some interfaces/functions on the server components and reusing them on client components as well.   What it was adding to the Client the server bundle and causing the error.

Moving them into a new file solved this issue.

**Comment by stipsan** [comment]
Good to hear @luigifgp! 🙌
