### ISSUE TITLE
Connection error after opening page from Presentation Tool in new tab

### ISSUE THREAD

**Issue by cwojcik-ifthen** [sanity-io/next-sanity#1950]
**Describe the bug**

When I navigate to a page within the iframed in site via the Presentation Tool, if I click "Open Preview" to open the page in a new tab wait a few seconds and then close the new tab, after a few more seconds the Presentation Tool presents a "connection" error message.

Chrome Dev Tools starts filling up with these "heartbeat" "no response" warnings:
```
[@sanity/comlink] Received no response to message 'comlink/heartbeat' on client 'presentation' (ID: 'msg-133f834f-2db1-4191-80c5-a6e35ae04f1c')
```

Something to do with Studio setting up a "connection" with the new tab which then fails?

**To Reproduce**

1. Go to a page within the Presentation Tool iframe
2. Click on "Open Preview"
3. Wait 10s and close the newly opened tab.
4. Wait ~10s and see error

**Expected behavior**

A user should be able to preview the site content in a new window without a connection error.

**Screenshots**

![Screen Shot 2024-11-20 at 4 35 00 PM](https://github.com/user-attachments/assets/80f63bcd-9d04-4aaf-9918-8fadec76c358)

![Screen Shot 2024-11-20 at 4 35 18 PM](https://github.com/user-attachments/assets/40b44370-6fac-4e08-9bda-2b33e914b949)

**Which versions of Sanity are you using?**

```
@sanity/cli (global)          3.64.1 (latest: 3.64.2)
@sanity/eslint-config-studio   4.0.0 (up to date)
@sanity/preview-url-secret     2.0.4 (up to date)
@sanity/vision                3.64.1 (latest: 3.64.2)
sanity                        3.64.1 (latest: 3.64.2)
```

**What operating system are you using?**

Mac OS v12.7.5

**Which versions of Node.js / npm are you running?**

```
10.7.0
v18.20.4
```

**Additional Context**

Would not think it matters, but: I am running both Studio and NextJS on localhost but Studio is not "embedded". I am more or less following this guide: https://www.sanity.io/docs/visual-editing-with-next-js-app-router-and-sanity-studio

I also ran through that guide separately rather than trying to integrate the Presentation Tool into my existing project just as a comparison and I experienced the same issue there too.

**Comment by rdunk** [comment]
#### Fixed in
https://github.com/sanity-io/visual-editing/pull/2194
#### Released in
https://github.com/sanity-io/visual-editing/releases/tag/presentation-v1.18.5
https://github.com/sanity-io/sanity/releases/tag/v3.65.0
