### ISSUE TITLE
`groq-js` may be incorrectly included in the client bundle

### ISSUE THREAD

**Issue by ricokahler** [sanity-io/next-sanity#22]
This issue stems from a community question regarding the client bundle size.

@chris-erickson [pointed out](https://sanity-io-land.slack.com/archives/C013NG0UF0B/p1623246607068400) that their next.js client build included groq-js.

`groq-js` is expected to show up as a dependency to `@sanity/groq-store` however it should be code-split and imported dynamically only when a sanity user is logged in.

This issue is an item to investigate that

**Comment by stipsan** [comment]
[We're working on a new version](https://github.com/sanity-io/next-sanity/pull/65) that lets you use `React.lazy` or `next/dynamic` to code-split away preview related code from your pages. Until they're actually needed :)

**Comment by stipsan** [comment]
We've just released [`v2.0.0`](https://github.com/sanity-io/next-sanity/releases/tag/v2.0.0) which has a new preview mode that no longer includes `groq-js` outside of previews 😌

**Comment by scottgrunerud** [comment]
@stipsan This is awesome y'all are killing it !! 🎊 💯
