### ISSUE TITLE
Error: Undefined function: dateTime when using live preview

### ISSUE THREAD

**Issue by tommyy** [sanity-io/next-sanity#23]
Seems to be related to #18 as I experience the exact same thing except here I'm using `dateTime` instead.

**Comment by judofyr** [comment]
This will be fixed once we release the next version of groq-js: https://github.com/sanity-io/groq-js/issues/41

**Comment by judofyr** [comment]
And then we need this one: https://github.com/sanity-io/groq-store/pull/3

**Comment by judofyr** [comment]
And once this is merged and released it should start finally working: https://github.com/sanity-io/next-sanity/pull/26

**Comment by judofyr** [comment]
This should work in version 0.3.0.
