### ISSUE TITLE
React Hook "usePreviewSubscription" is called conditionally. React Hooks must be called in the exact same order in every component render

### ISSUE THREAD

**Issue by nandotess** [sanity-io/next-sanity#24]
[Next.js 11 now supports ESLint out of the box.](https://nextjs.org/blog/next-11#conformance)

After upgrading to Next.js 11 and installing/running ESLint, there is one issue related to `next-sanity` that I'm not quite sure how to solve:
```
Error: React Hook "usePreviewSubscription" is called conditionally. React Hooks must be called in the exact same order in every component render.  react-hooks/rules-of-hooks
```

This is happening because of this `return ErrorPage` we have here:
```
  if (!router.isFallback && !data.post?.slug) {
    return <ErrorPage statusCode={404} />
  }

  const {data: post} = usePreviewSubscription(postQuery, {
    params: {slug: data.post.slug},
    initialData: data.post,
    enabled: preview,
  })
```

One possible solution that I found is to make `usePreviewSubscription` to accept a function like `useEffect` does so it's possible to call `usePreviewSubscription` sooner in the component and inside the passed function, use the condition `!router.isFallback && !data.post?.slug`.

**But this is a guess**. I would like to hear from experienced developers so we know how to make this code 100% compatible with React standards.

**Comment by tommyy** [comment]
I've simply moved 

```
  if (!router.isFallback && !data.post?.slug) {
    return <ErrorPage statusCode={404} />
  }
  ```
  
underneath `usePreviewSubscription` as they do in this example by Vercel:
https://github.com/vercel/next.js/blob/canary/examples/cms-sanity/pages/posts/%5Bslug%5D.js

**Comment by nandotess** [comment]
So maybe the `next-sanity` documentation/recommendation should be updated to match this pattern? If the `sanity-io` team approves it, for sure... =)

**Comment by judofyr** [comment]
@nandotess: Does this example work better? https://github.com/sanity-io/next-sanity/pull/25

**Comment by rodeok** [comment]
haha
