### ISSUE TITLE
Can't deploy because of dependency issue

### ISSUE THREAD

**Issue by vincentjflorio** [sanity-io/next-sanity#263]
This is likely being worked on already but this package's current  preview-kit dependency is a couple minor releases behind one that addresses a missing file and directory; that repo just got updated to address it:
https://github.com/sanity-io/preview-kit/pull/127

Until next-sanity is reconciled (absent other guidance), that seems to affect our ability to build out:

`Cannot find module '/vercel/path0/node_modules/.pnpm/next-sanity@3.1.9_r34pbuycespj3pgrjn6rawo43a/node_modules/@sanity/preview-kit/node/index.js' imported from /vercel/path0/node_modules/.pnpm/next-sanity@3.1.9_r34pbuycespj3pgrjn6rawo43a/node_modules/next-sanity/dist/preview.js`

Copying and pasting the files resolves the issue but that won't work for a Vercel build relying on accurate versions, and deleting the existing version (or /node_modules/ itself) and reverting doesn't seem to affect things easier.

EDIT: Changed explanation for clarity

**Comment by mariuslundgard** [comment]
Hi @vincentjflorio, you're spot on – it should be fixed in `@sanity/preview-kit@1.2.17`. Let us know if you still encounter this issue.

**Comment by vincentjflorio** [comment]
What I meant to say is, because the latest next-sanity uses

**Comment by mariuslundgard** [comment]
OK, I see. Since `next-sanity` depends on `@sanity/preview-kit@^1.12.15` (with the `^`) it should resolve to `@sanity/preview-kit@^1.12.17` automatically. If you're deploying with Vercel, you might need to deselect the "Redeploy with existing Build Cache" option.

**Comment by vincentjflorio** [comment]
Thanks, @mariuslundgard . I will give it a shot right now and report back.

**Comment by vincentjflorio** [comment]
@mariuslundgard That did the trick. Thank you for your time and patience.

**Comment by mariuslundgard** [comment]
Good to hear, sorry for the inconvenience!
