### ISSUE TITLE
PublicAccessOnly error

### ISSUE THREAD

**Issue by Pandeyashish17** [sanity-io/next-sanity#278]
I am logged in but i am still getting an error for preview mode
![image](https://user-images.githubusercontent.com/102592319/211526689-ac8aee4c-1d6a-46c2-ae3c-7d838e48e01b.png)

`"use client";

import { definePreview } from "next-sanity/preview";
import { projectId, dataset } from "./sanity.client";

function onPublicAccessOnly() {
  throw new Error(`Unable to load preview as you're not logged in`);
}

if (!projectId || !dataset) {
  throw new Error(
    "Missing ProjectId or dataset. Check your sanity.json or .env"
  );
}

export const usePreview = definePreview({
  projectId,
  dataset,
  onPublicAccessOnly,
});
`

**Comment by stipsan** [comment]
You're likely affected by the conditions documented in the `Cons` section here: https://github.com/sanity-io/next-sanity#built-in-sanity-auth

The way to solve it is by implementing the custom auth pattern: https://github.com/sanity-io/next-sanity#custom-token-auth

This pattern is implemented in our Next 13 blog starter: https://github.com/sanity-io/nextjs-blog-cms-sanity-v3
