### ISSUE TITLE
Websocket doesnt get closed in Firefox for the usePreviewSubscription hook

### ISSUE THREAD

**Issue by PetterRuud** [sanity-io/next-sanity#32]
The connection to https://dz15n411.api.sanity.io/v1/data/listen/production?query=*&effectFormat=mendoza was interrupted while the page was loading.
node_modules_sanity_groq-store_dist_browser_groq-store_js.js:9:808

Firefox bug
https://bugzilla.mozilla.org/show_bug.cgi?id=712329

Temp solution
https://stackoverflow.com/questions/14140414/websocket-was-interrupted-while-page-is-loading-on-firefox-for-socket-io/23784296#23784296

**Comment by judofyr** [comment]
The bug you linked to seemed to have already been fixed. What version of Firefox are you seeing this in?

**Comment by PetterRuud** [comment]
> 
> 
> The bug you linked to seemed to have already been fixed. What version of Firefox are you seeing this in?
running 
- Firefox Developer 92.0beta, but the problem has existed for a few versions now. 
- next-sanity: 0.4.0

**Comment by stipsan** [comment]
Closing as it's stale but please feel welcome to re-open if it's still happening in `v0.6.x` :)
