### ISSUE TITLE
Something is missing in next-sanity package?

### ISSUE THREAD

**Issue by WillPwn4Food** [sanity-io/next-sanity#33]
I've done a "yarn add next-sanity" and as soon as I add:

import { groq } from 'next-sanity'

I get the following errors:

error - ./node_modules/@sanity/client/lib/sanityClient.js:27:0
Module not found: Can't resolve './assets/assetsClient'

Not sure what step I might be missing.

**Comment by judofyr** [comment]
What version of `@sanity/client` are you using? You can check this by looking in `node_modules/@sanity/client/package.json` or inside the yarn.lock file.

**Comment by WillPwn4Food** [comment]
If I go into my node_modules like you said into the package.json:

"name": "@sanity/client",
  "version": "2.19.0",
  "description": "Client for retrieving data from Sanity",

**Comment by stipsan** [comment]
Closing as it's since been resolved :)
