### ISSUE TITLE
Update Next 13 app dir usage to use new metadata API

### ISSUE THREAD

**Issue by AndrewIngram** [sanity-io/next-sanity#333]
Next has deprecated the `head.{js,tsx}}` module in favour of a new metadata export API (https://beta.nextjs.org/docs/api-reference/metadata), the current next-sanity instructions refer to using head.tsx.

**Comment by patrickedqvist** [comment]
Using the studio with the recent [v13.2](https://nextjs.org/blog/next-13-2) causes the studio to crash. Any ETA on the implementation of the new metadata API?

**Comment by patrickedqvist** [comment]
Yes I did find one today actually.

1. Remove the head.tsx file
2. Create a layout.tsx file
3. Insert the following

```.tsx
import type {PropsWithChildren} from "react";
import type {Metadata} from "next";


/**
 * Temporary workaround for setting metadata for the Studio.
 * implemented necessary data according to the following source code: https://github.com/sanity-io/next-sanity/blob/main/src/studio/head/NextStudioHead.tsx
 * @todo remove this workaround when the issue is fixed
 * @see https://github.com/sanity-io/next-sanity/issues/333
 */
export const metadata: Metadata = {
  title: 'Studio | EGGS Wiki',
  viewport: 'width=device-width,initial-scale=1,viewport-fit=cover',
  robots: 'noindex',
}

export default function StudioLayout({ children }: PropsWithChildren) {
  return children;
}
```
You won't get some things that are listed in the [original head.tsx](https://github.com/sanity-io/next-sanity/blob/main/src/studio/head/NextStudioHead.tsx) but you will get the most important things.

**Comment by JohnGemstone** [comment]
My issue was unrelated, the "crash" I experienced was an application error:

```
There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.
```

After a lot of debugging I realised I missed the important 
```
swcMinify: false,
```
in my next config.

All working! Thank you.

Hopefully this helps someone on the way.
