### ISSUE TITLE
Live preview for pages other than the index page

### ISSUE THREAD

**Issue by nizam0786** [sanity-io/next-sanity#334]
Hi there,

Thanks for the Amazing Package. Just wondering how can we use the live preview per a post. I have it working for the index page but can get the preview working for when I just want to preview a single post.

I keep getting the following error:
TypeError: useReducer only works in Client Components. Add the "use client" directive at the top of the file to use it.

**Comment by stipsan** [comment]
Hi, give this a look: https://github.com/sanity-io/sanity-template-nextjs-appdir-personal-website/blob/main/app/(personal)/projects/%5Bslug%5D/page.tsx

Other than that, based on the error message it sounds like you need to add `use client` at the top of the file that exports a React component that calls the `usePreview` hook :relaxed:

**Comment by nizam0786** [comment]
Thanks for sharing the repo. I'll have a look. I have added use client to everywhere I have used usePreview but still no luck :( 

<img width="1025" alt="Screenshot 2023-02-15 at 00 12 23" src="https://user-images.githubusercontent.com/16906888/218892202-2dd4bcd4-623e-4e84-a32e-41eedfdcb3f7.png">

**Comment by nizam0786** [comment]
<img width="704" alt="Screenshot 2023-02-15 at 00 14 11" src="https://user-images.githubusercontent.com/16906888/218892430-0e252361-8f44-46c2-aad8-708be91e9067.png">
<img width="527" alt="Screenshot 2023-02-15 at 00 14 33" src="https://user-images.githubusercontent.com/16906888/218892475-9fbc9bec-a31c-45e4-a4c9-3978469ddf8e.png">

**Comment by nizam0786** [comment]
By the way although this has given me a headache Sanity is so Amazing!

**Comment by nizam0786** [comment]
Ah it was because I was using the wrong PreviewSuspence component. Thanks for pointing me in the right direction 👍

**Comment by stipsan** [comment]
Happy to hear you figured it out @nizam0786! 🎉
