### ISSUE TITLE
'SanityClient' is not assignable to parameter of type 'SanityClientLike'

### ISSUE THREAD

**Issue by schellenbergk** [sanity-io/next-sanity#347]
```
import { createClient } from 'next-sanity';
import { useNextSanityImage } from 'next-sanity-image';

const client = createClient({
  dataset: 'production',
  projectId: '...',
  useCdn: false,
  apiVersion: '2022-11-15'
});

const props = useNextSanityImage(client, photo);
```
Typescript complains:
```
Argument of type 'SanityClient' is not assignable to parameter of type 'SanityClientLike'
```

**Comment by aaronbentley** [comment]
Hey @schellenbergk 👋,

I ran into the same issue and raised it in the `next-sanity-image` repo, you can track [the progress here](https://github.com/lorenzodejong/next-sanity-image/issues/53).

**Comment by stipsan** [comment]
Hi, the new v6 release of `next-sanity-image` fixes this problem: https://github.com/lorenzodejong/next-sanity-image/releases/tag/6.0.0 🎉
