### ISSUE TITLE
Unhandled Error: 'use client'

### ISSUE THREAD

**Issue by oluwadaprof** [sanity-io/next-sanity#366]
Unhandled Runtime Error
Error: useReducer only works in Client Components. Add the "use client" directive at the top of the file to use it. Read more: https://nextjs.org/docs/messages/react-client-hook-in-server-component

![next error](https://user-images.githubusercontent.com/57744795/225488154-0a6e8356-5531-4d1e-a6ba-70415d7cc9ef.jpg)

Added the 'use client' at the top of the file at the appropriate directory yet it's still not working.

**Comment by stipsan** [comment]
Hi 👋 

> Added the 'use client' at the top of the file at the appropriate directory yet it's still not working.

Then it sounds like there's a couple more instances you need to add it to.
The surefire approach is to add `use client` to every file where you have an import from `next-sanity/studio`, `next-sanity/preview` or `@sanity/preview-kit` and that should solve the error.
This might lead to more instances of `use client` than you need, so if you want to optimise your app to make the most use of server components you could check them, one by one, to find out which instances you can remove them from 🙂
