### ISSUE TITLE
Strange "poisoning" behavior with appDir and previewing

### ISSUE THREAD

**Issue by JohnGemstone** [sanity-io/next-sanity#380]
Sometimes components act like they have ['use client'](https://beta.nextjs.org/docs/rendering/server-and-client-components#client-components) enabled and spill out onto the client. I've created a [reproduction](https://github.com/JohnGemstone/sanity-template-nextjs-appdir-personal-website_poison) using the [`sanity-template-nextjs-appdir-personal-website`](https://github.com/sanity-io/sanity-template-nextjs-appdir-personal-website) template. My repo introduces 'react-icons' to show the difference a bit more clearly.

-----

Here is the site working as expected:
[Vercel Deployment](https://sanity-template-nextjs-appdir-personal-w-git-baa80a-jimjohnston.vercel.app/test-page)
[Git Repo](https://github.com/JohnGemstone/sanity-template-nextjs-appdir-personal-website_poison/tree/with-homepage)
![image](https://user-images.githubusercontent.com/17420741/226974905-fcb8b75d-35be-4191-ad6e-00d7a3388206.png)
Note: 445kB resources loaded

-----

Here is the site when 'poisoned':
[Vercel Deployment](https://sanity-template-nextjs-appdir-personal-website-poison.vercel.app/test-page)
[Git Repo](https://github.com/JohnGemstone/sanity-template-nextjs-appdir-personal-website_poison/)
![image](https://user-images.githubusercontent.com/17420741/226975589-63a9f03d-4615-4bce-87ae-36fb931fafd4.png)
Note: 5.0MB resources loaded

-----

The only difference between the two is a homepage that fetches. 

```tsx
//app/(personal)/page.tsx

import { getHomePage } from 'lib/sanity.client'
import { getPreviewToken } from 'lib/sanity.server.preview'
import { notFound } from 'next/navigation'
export default async function IndexRoute() {
  const data = (await getHomePage({ })) || {
    title: '',
    overview: [],
    showcaseProjects: [],
  }
  if (!data ) {
    notFound()
  }
  return (
    <>
      <div>
        homepage
      </div>

      {/* bring back HomePage component and poison is fixed */}
      {/* <HomePage data={data} /> */}

    </>
  )
}
```

[Compare Branches](https://github.com/JohnGemstone/sanity-template-nextjs-appdir-personal-website_poison/compare/with-homepage?expand=1#diff-698fb92fb8c49421695724117619501aa7426fc57b88b562f92eff41bd86ec26L28)

-----

Has anyone else experienced this? The behaviour is slippery and it took me a while to pin down these reproductions.
AppDir is still in beta, so this is could be more of a NextJS issue, but they would require a minimal reproduction (without preview kit probably) to pinpoint the bug. For now, I think my best bet is to make two seperate branches, one with previews for editors (with the leaks) and one without preview for production. Thanks!

**Comment by JohnGemstone** [comment]
I should have mentioned in the description that the components are leaking from the [PreviewSuspense component](https://github.com/JohnGemstone/sanity-template-nextjs-appdir-personal-website_poison/blob/with-homepage/app/(personal)/%5Bslug%5D/page.tsx#L32) e.g.

```tsx
// app/(personal)/[slug]/page.tsx 

  return (
    <>
      {token ? (
        <PreviewSuspense
          fallback={
            <PreviewWrapper>
              <Page data={data} />
            </PreviewWrapper>
          }
        >
          <PagePreview token={token} slug={params.slug} /> // here
        </PreviewSuspense>
      ) : (
        <Page data={data} />
      )}
    </>
  )
  ```
More specifically from [inside the PagePreview component](https://github.com/JohnGemstone/sanity-template-nextjs-appdir-personal-website_poison/blob/with-homepage/components/pages/page/PagePreview.tsx#L20).
Which is why it feels bizarre that commenting out an unrelated component, from another route can cause this behavior.
🤔

**Comment by stipsan** [comment]
Circling back, in v5 we have reduced the impact of this by replacing the `PreviewSuspense` pattern with a [custom `PreviewProvider` that implements a `LiveQueryProvider`](https://github.com/sanity-io/next-sanity/blob/main/PREVIEW-app-router.md).
In this setup you should not expect production code (as in `draftMode().isEnabled === false`) to result in an increase in components pushed to the client once live previews are implemented in the codebase.
That said, it's to be expected that when `draftMode().isEnabled === true` every component that uses `use client` and `useLiveQuery` will cause a lot of code to now run in the client. This is not a bug, but a "feature" as it's the only way to re-render the view in real-time as Server Components aren't built for this pattern.
