### ISSUE TITLE
useGroqBeta breaks preview

### ISSUE THREAD

**Issue by heggemsnes** [sanity-io/next-sanity#39]
Hi

We really love live preview and view it as one of the "wow" moments when showing off Sanity to clients.

Unfortunately for a lot of our projects the query size causes the browser to basically break so we've had to stop using this approach. Therefore we are really excited about his beta!

Using  `"next-sanity": "^0.4.1-beta.0"` the preview works great as intended. But when adding:
```
export const usePreviewSubscription = createPreviewSubscriptionHook({
  ...config,
  useGroqBeta : true
})
```

It just stops working without any errors.

**Comment by nboliver** [comment]
@heggemsnes Do you have the hook configured to return error? 
```
const { data, loading, error } = usePreviewSubscription(query, { ... 
```
When adding `useGroqBeta : true` and logging out the error, I get the following error: 
```
react_devtools_backend.js:4061 ReferenceError: marks is not defined
    at parseString (groq-js.esm.js?4826:1497:1)
    at parseObject (groq-js.esm.js?4826:1442:1)
    at parseExpr (groq-js.esm.js?4826:862:1)
    at parse$1 (groq-js.esm.js?4826:784:1)
    at parse (groq-js.esm.js?4826:2796:1)
    at eval (groq-store.js?181b:1:5227)
```
When I remove `useGroqBeta : true` it works most of the time, but it's slow.

**Comment by stipsan** [comment]
Closing this as the `marks is not defined` were resolved a few versions back when we upgraded from the beta. :)
The slowness issue is still a known issue. And if you have a repro case feel free to share it, much appreciated 🙇
