### ISSUE TITLE
How to make TOC?

### ISSUE THREAD

**Issue by narr07** [sanity-io/next-sanity#435]
iam using next 13

**Comment by sebpowell** [comment]
@narr07 – this worked for me: https://kittygiraudel.com/2022/05/19/table-of-contents-with-sanity-portable-text/

**Comment by mustaquenadim** [comment]
> @narr07 – this worked for me: https://kittygiraudel.com/2022/05/19/table-of-contents-with-sanity-portable-text/

It doesn't provide whole solutions like it doesn't connect table of contents' anchor tags with the page headings.

**Comment by stipsan** [comment]
Closing as it's not technically related to `next-sanity`, [our Slack community are a great place to ask questions like these :) ](https://slack.sanity.io/)
