### ISSUE TITLE
image.asset->url returns null

### ISSUE THREAD

**Issue by stitot** [sanity-io/next-sanity#443]
When in preview mode `image.asset->url` returns `null`

`image.asset` works fine, and returns the correct object with `_ref` and `_type`, but when appending` ->url` it returns `null`

Works fine when not in preview mode

**Comment by stipsan** [comment]
This isn't enough information to help us help you. I'm closing this issue for now but feel free to re-open if you can provide us with a link to a codesandbox or a github repo where we can reproduce the problem :)
