### ISSUE TITLE
How to return draft posts?

### ISSUE THREAD

**Issue by sebpowell** [sanity-io/next-sanity#448]
I followed the Readme guide to get preview mode working, but there's one thing I'm not sure about, hoping someone might be able to point me in the right direction.

The query I'm using the fetch my post in preview mode looks like this:

```
*[_type == "post" && slug.current == $slug][0]{ ..., authors[]->, categories[]->]
```

This however, doesn't bring back any posts that are in draft mode, only posts that are published are returned, which seems to defeat the purpose. I couldn't find anything in the docs that explains how to include draft posts in the response, so I'm wondering if I'm going about this in the right way. Should it be the case, instead, that posts have a field called, say 'publishedAt', which is used to filter out posts on the main site that haven't yet been published?

Any pointers would be greatly appreciated.

**Comment by stipsan** [comment]
Hi! You seem to be missing a `token` in your `createClient` call perhaps?

It sounds like you're trying out Sanity for the first time, if so I highly recommend our community and support staff over on our [Slack](https://slack.sanity.io/) 😄
