### ISSUE TITLE
Preview performance

### ISSUE THREAD

**Issue by Ojay** [sanity-io/next-sanity#453]
Hey everyone,

Not necessarily an issue per-se as Sanity/Next previews are technically working, they just do so in a manner that is almost unusable. Here's a video illustrating the lag I'm experiencing: https://capture.dropbox.com/TMHRVI3ya2znIDmR
(In the video,  finished typing as soon as I start moving the cursor).

This is a clean install of the [nextjs-blog-cms-sanity-v3](https://github.com/sanity-io/nextjs-blog-cms-sanity-v3) repo. I've added our data set, duplicated the `post` related components and set them up to work with a `feature` content type within the data set.

I've limited the `documentList` in the `definePreview` config to 1,000 and have limited it to only include the `feature` type.

```
import { dataset, projectId } from 'lib/sanity.api'
import { definePreview } from 'next-sanity/preview'

let alerted = false
export const usePreview = definePreview({
  projectId,
  dataset,
  onPublicAccessOnly: () => {
    if (!alerted) {
      // eslint-disable-next-line no-alert
      alert('You are not logged in. You will only see public data.')
      alerted = true
    }
  },
  documentLimit: 1000,
  includeTypes: ['feature'],

})

```
Our dataset has a little over 9,000 documents in it. I know optimisations are coming to the plugin, but as is, it seems the previews feature is just not appropriate for use on larger sites. 

Any further ideas on getting this to work a little quicker on datasets of this size or is this just how it is? If so it may be worth adding a more obvious flag to the readme so people with larger datasets are aware.

Thanks for all you guys do, Sanity is an absolute dream!

**Comment by stipsan** [comment]
Hi, really appreciate the detailed report and the recording! 
We're working on a new mode and this is useful data to add to our long list over end to end tests 🙌 

I'll come back to this thread when you can test it

**Comment by Ojay** [comment]
Ahh amazing, glad to hear it :-)
I'll continue with the integration in the assumption that if/when the new mode is released it should be easy enough to upgrade.

Thanks for getting back to me,

Mark

**Comment by stipsan** [comment]
[We got some good news.](https://www.sanity.io/blog/introducing-perspectives-sanity-previews)

[A v5 of `next-sanity` is out that builds upon these new features.](https://github.com/sanity-io/next-sanity/releases)
