### ISSUE TITLE
Preview mode with multiple queries on single page & page flickering

### ISSUE THREAD

**Issue by AdisonCavani** [sanity-io/next-sanity#461]
1st issue:

I'm using Next.js 13 with draft mode (a.k.a. preview mode).
I'm making 3 queries on single page.

If I wrap my whole page then I'm getting a page flicker (only in preview mode) - whole page is blank (for ~ 1 sec) and then it's re-rendering with updated preview content.
```tsx
// page-preview.tsx
const posts = usePreview(null, blogQuery);
const items = usePreview(null, itemsQuery);
const categories = usePreview(null, techCategoryQuery);

return <HomePage posts={posts} items={items} categories={categories} />
```

How should I approach this problem?
Should I wrap each component that requires query in a separate manner?

**Comment by stipsan** [comment]
[This issue should be resolved in v5](https://github.com/sanity-io/next-sanity/releases/tag/v5.0.0) when [combined with `perspective: previewDrafts`.](https://www.sanity.io/blog/introducing-perspectives-sanity-previews)
