### ISSUE TITLE
Embedded studio with Next app dir and `output: 'export'`

### ISSUE THREAD

**Issue by IngoValente** [sanity-io/next-sanity#471]
I'm using the Next.js app router and the option to statically export my website using the `output: 'export'` option in my next.js config.
Pages are generated with `generateStaticParams`.
I've tried embedding the sanity studio in the app dir following the readme, but on build Next.js refuses to make the /studio part of the website static. When I setup the studio in the pages folder, everything gets generated statically. Any tips on getting this working?

**Comment by hawlinbuttzbbq** [comment]
I am having the same issue

**Comment by stipsan** [comment]
Add `export const dynamic = 'force-static'` to your `app/studio/[[...tool]]/page.tsx` route :)
