### ISSUE TITLE
Invalid signature Error

### ISSUE THREAD

**Issue by jasan-s** [sanity-io/next-sanity#483]
Nvm.... just me being stupid

_Originally posted by @Gawdfrey in https://github.com/sanity-io/next-sanity/issues/423#issuecomment-1535990869_
            

How did you resolve this? I'm still getting invalid signature. Environment secret matches the sanity webhook secret.

**Comment by Gawdfrey** [comment]
The exact issue I had with that code was that I was just checking if my env var secret was present 😓 Not if the incoming request secret was the same as the env var secret
<img width="522" alt="image" src="https://github.com/sanity-io/next-sanity/assets/46612252/b7728219-0bde-48b1-9c41-d6a0e4588ba5">

The way I ended up doing it was having no secret at all and just checking the signature via the sanity webhook package.

**Comment by jasan-s** [comment]
i found the issue, not sure how to solve it though:

SO i deployed ,my Next JS sanity app to Firebase hosting: 

For some reason the Body is empty in deployed env:

```
    const { body, isValidSignature } = await parseBody(
      req,
      process.env.SANITY_REVALIDATE_SECRET
    )
    // if (isValidSignature === false) {
    //   const message = 'Invalid signature'
    //   console.log(message)
    //   return res.status(401).send(message)
    // }

    console.log('Received body', JSON.stringify(body, null, 2))
```

>Received body ""


locally in development it is working.

**Comment by Gawdfrey** [comment]
Any reason for not hosting on [Vercel](https://vercel.com)?
I will assume that firebase mangles the body in some way. Maybe look into if there is any body parsers or like in firebase that can affect this.

**Comment by stipsan** [comment]
It's unclear what we can do on our end to aid here.
I would suggest trying to use the [`@sanity/webhook`](https://github.com/sanity-io/webhook-toolkit) package directly and once you find a working configuration we could look at if that's something we can cater to out of the box 😄
