### ISSUE TITLE
Getting continous "TypeError: Converting circular structure to JSON" error while using next studio in chrome

### ISSUE THREAD

**Issue by basilmuhammed** [sanity-io/next-sanity#484]
I have this issue while using next sanity in chrome with the latest version of next sanity.

![image](https://github.com/sanity-io/next-sanity/assets/63568802/49c5d401-d21e-4f0a-872a-f142081eff15)

backend.bundle.js:1 Uncaught (in promise) TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'HTMLButtonElement'
    |     property '__reactFiber$xhne86i5jmj' -> object with constructor 'FiberNode'
    --- property 'stateNode' closes the circle
    at JSON.stringify (<anonymous>)

**Comment by stipsan** [comment]
Can't reproduce this issue.
