### ISSUE TITLE
Live preview not working properly in production mode

### ISSUE THREAD

**Issue by zarif-al** [sanity-io/next-sanity#490]
Hi. I am working on a Next 13 & Sanity project. I set it up following your app router guide posted [here](https://github.com/sanity-io/next-sanity/blob/main/PREVIEW-app-router.md). 

Everything works as expected in `dev` mode. I am able preview draft content and see real time updates.

However in `production` I am not getting live updates in preview mode. I have to refresh the page to see the latest draft content. I get this error on the  front end when I update content on sanity.

![image](https://github.com/sanity-io/next-sanity/assets/71602715/27ae410a-e8de-4960-b4f5-2c07ed74c5bd)

The preview mode will show have live updates for first few seconds of the page rendering. Then I will start to see this error.

Because this issue only happens in `production` I don't know where to begin debugging.

My package versions
```
"next": "^13.4.11",
"next-sanity": "^5.1.2",
"@sanity/client": "^6.1.7",
```

**Comment by matkarlg** [comment]
I upgraded to Next 13.4.11 and got this problem.
Went back to 13.4.9 and it works again.
