### ISSUE TITLE
Version incompatibilities between Next.js 13.9+ and Sanity

### ISSUE THREAD

**Issue by Kapple14** [sanity-io/next-sanity#492]
First of all thanks for providing us with such a strong platform for content creation! I have had some issues regarding the deployment of Sanity Studio with Next.js 13.9+ on Netlify. The overall site worked, but my included blog did not launch and throw a severe error: 500. Regarding the error messages I can state that this is a version incompatibility of the semver version used by Next internally. I hope that this helps.

**Comment by stipsan** [comment]
Are you able to share the same error messages you sent me by DM? :)
