### ISSUE TITLE
Unauthenticated users can access cms (read-only), with no option to login

### ISSUE THREAD

**Issue by danlutz** [sanity-io/next-sanity#514]
I upgraded to the latest version today and invited a new cms user. When the user accessed the cms route, he immediatly had access to the "Desk" page, but was not able to login with his real account.

Dependencies:
```json
{ 
"dependencies": {
		"@headlessui/react": "^1.7.16",
		"@heroicons/react": "^2.0.18",
		"@portabletext/react": "^3.0.4",
		"@sanity/client": "^6.4.3",
		"@sanity/image-url": "^1.0.2",
		"@sanity/vision": "^3.14.5",
		"framer-motion": "^10.15.1",
		"groqd": "^0.15.7",
		"groqd-playground": "^0.0.15",
		"next": "13.4.13",
		"next-sanity": "^5.2.2",
		"pure-react-carousel": "^1.30.1",
		"react": "18.2.0",
		"react-dom": "18.2.0",
		"sanity": "^3.14.5",
		"sanity-plugin-asset-source-unsplash": "^1.1.0",
		"styled-components": "^6.0.7"
}
```

Hosted on Vercel, configured according to the example in this repo. Yesterday it worked perfectly fine.

Lmk if you need any other information!

**Comment by stipsan** [comment]
Are you using `unstable_noAuthBoundary` anywhere?

**Comment by danlutz** [comment]
Oh shit, i actually do! Sorry, bug can be closed.

I was looking for the implementation using the AppRouter, and copy pasted this file:

https://github.com/sanity-io/next-sanity/tree/main/app/studio/%5B%5B...tool%5D%5D

Sorry, thanks for pointing it out!
