### ISSUE TITLE
TypeError: styled_components__WEBPACK_IMPORTED_MODULE_3__.div is not a function

### ISSUE THREAD

**Issue by prodz18** [sanity-io/next-sanity#515]
Hi guys,
I noticed this error since version `5.2.1` (also happening in `5.2.2`):
`
error node_modules/next-sanity/dist/studio/index.js (23:21) @ eval
error TypeError: styled_components__WEBPACK_IMPORTED_MODULE_3__.div is not a function
`
It doesn't happen on version `5.2.0`
Hope that helps.

**Comment by stipsan** [comment]
Seems like the core issue were this: https://github.com/vercel/next.js/issues/53723
