### ISSUE TITLE
Sanity Vercel Integration Broken

### ISSUE THREAD

**Issue by russellchapin** [sanity-io/next-sanity#527]
Hello, I’ve been trying to add Sanity as a Vercel integration for a Next deployment, but the Sanity login pop up window appears to be broken. It’s giving a 401 and I cannot click on any of the auth options to continue. As you can see, the page appears to be broken. I’ve tried multiple browsers, etc. 
![IMG_1493](https://github.com/sanity-io/next-sanity/assets/9587103/f94ebce0-74f9-4b1c-95de-5d5be177804e)

**Comment by stipsan** [comment]
Should be back working now! 🙌
