### ISSUE TITLE
Getting undefined when fetching data from sanity studio in latest nextjs

### ISSUE THREAD

**Issue by abdulhadi240** [sanity-io/next-sanity#539]
This is a simple homepage where i fetch data from serversideprops . all the info here is correct .But i am still getting undefined.
![e1](https://github.com/sanity-io/next-sanity/assets/70109681/62f152f4-271c-4ee2-947f-56e48350731a)
Here is the Screenshot of the data i should receive.
![e2](https://github.com/sanity-io/next-sanity/assets/70109681/317d538a-9a1f-41d4-baf4-e5505017d75e)
This s the config file of sanity.
![e3](https://github.com/sanity-io/next-sanity/assets/70109681/48900e11-d179-479c-8d23-590972099ee9)

**Comment by stipsan** [comment]
Hi, thanks for the detailed report!

It seems to work on my end though: https://codesandbox.io/p/sandbox/nextjs-gssp-repro-lp65k8

I see you have `useCdn: true`, this means it may take a while for you to see new content (10 - 15 minutes). You can set it to `useCdn: false` during development to avoid confusion, that's what the "Vision Tool" is doing :)

I highly recommend you [join our Slack](https://slack.sanity.io/) to get more help as you're digging into Sanity.
