### ISSUE TITLE
Support edge runtime in next-sanity/webhook

### ISSUE THREAD

**Issue by marcusforsberg** [sanity-io/next-sanity#587]
Recently [a change was made](https://github.com/sanity-io/next-sanity/commit/ecf96fb0a18868e8fb3346011af78faf22f8aabd) to make next-sanity/webhook throw an error when running on the Edge runtime, whereas previously the signature verification would silently fail.

This is a welcome change to make it clear that the Edge runtime not supported, but are there any plans to support it in the future?

**Comment by stipsan** [comment]
We don't have it on our immediate roadmap, no. While there are performance benefits to addressing this, we feel we have other pressing priorities with a higher ROI right now.

That said, if any brave soul were to submit a PR to https://github.com/sanity-io/webhook-toolkit adding support, we'll fast track reviewing it and get it released 🙌

**Comment by danteissaias** [comment]
@stipsan I've opened a [pull request](https://github.com/sanity-io/webhook-toolkit/pull/40) with code from https://github.com/sanity-io/webhook-toolkit/issues/38#issuecomment-1794943884. Please let me know once you've had a chance to review this.
