### ISSUE TITLE
Package does not work on IE11 in Next.js

### ISSUE THREAD

**Issue by VWSCoronaDashboard** [sanity-io/next-sanity#6]
Hi Sanity 👋 !

Today while running a browser-test we found out some output in our bundle [that crashed IE11](https://github.com/minvws/nl-covid19-data-dashboard/pull/1535). 

To solve it, I replaced `next-sanity` with `@sanity/client` and `@sanity/block-content-to-react` and now our build works without any problems.

https://github.com/minvws/nl-covid19-data-dashboard/pull/1540

Is this happening because `next-sanity` ships ES6 code and `@sanity/client` and `@sanity/block-content-to-react` ship ES5 code?

**Comment by rexxars** [comment]
@VWSCoronaDashboard Hi - thanks for reporting! Do you know what exactly it was that crashed?

**Comment by jarandmi** [comment]
I got the same error reported by Sanity in IE11.
It looks like it's a syntax error in the arrow functions. As i remember i IE11 don't support this.

>  … .yarn/cache/picosanity-npm-2.1.2-81d446d0b5-b4e5f34d49.zip/node_modules/picosanity/lib/client.js at line 17:123

`17. ['clone', 'create', 'createIfNotExists', 'createOrReplace', 'delete', 'listen', 'mutate', 'patch', 'transaction'].forEach(method => {`

**Comment by rexxars** [comment]
Version 0.1.10 has some upgraded dependencies that should fix this, thanks for reporting!
