### ISSUE TITLE
ReferenceError: liveQuery__namespace is not defined

### ISSUE THREAD

**Issue by georgebutter** [sanity-io/next-sanity#653]
Hi, I’m trying to migrate my project from using usePreview to use the LiveQuery component instead. I’m following [this structure](https://github.com/sanity-io/next-sanity/blob/main/PREVIEW-pages-router.md#after) but when I load my page I get the following error:
`ReferenceError: liveQuery__namespace is not defined`

from this file: node_modules/next-sanity/dist/preview/live-query.cjs on line `10`

```
'use strict';

Object.defineProperty(exports, '__esModule', {
  value: true
});
var liveQuery = require('@sanity/preview-kit/live-query');
Object.defineProperty(exports, 'default', {
  enumerable: true,
  get: function () {
    return liveQuery__namespace.default;
  }
});
Object.keys(liveQuery).forEach(function (k) {
  if (k !== 'default' && !Object.prototype.hasOwnProperty.call(exports, k)) Object.defineProperty(exports, k, {
    enumerable: true,
    get: function () {
      return liveQuery[k];
    }
  });
});
//# sourceMappingURL=live-query.cjs.map
```

The only way I was able to get it working was to import LiveQuery directly from `@sanity/preview-kit/live-query`

**Comment by stipsan** [comment]
Can you try setting `swcMinify: false`?
