### ISSUE TITLE
Vercel build fails because of "parseBody" webhook

### ISSUE THREAD

**Issue by BraveVN** [sanity-io/next-sanity#708]
**Describe the bug**

I cloned a simple blog project from this [Stablo template](https://github.com/web3templates/stablo), then add revalidate (slug) to the code & deploy to Vercel. Build error at `parseBody` method: `Type error: Expected 0 type arguments, but got 1.`

**To Reproduce**

1. Add [caching revalidate](https://github.com/sanity-io/next-sanity#slug-based-revalidation-for-the-pages-router) to your project, in my situation, I use the [example code](https://github.com/sanity-io/sanity-template-nextjs-app-router-personal-website/blob/main/app/api/revalidate/route.ts) by Sanity team
2. Deploy to Vercel to trigger the auto build
3. See error: `Type error: Expected 0 type arguments, but got 1.`

**Expected behavior**

Build passes

**Screenshots**

![image](https://github.com/sanity-io/sanity-template-nextjs-app-router-personal-website/assets/9208330/0ba8fbd6-3ff6-4f06-9320-1016fa4bf1c0)

**Which versions of Sanity are you using?**

Please see the `package.json` file here: 
```
{
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "postbuild": "next-sitemap",
    "start": "next start",
    "sanity": "sanity dev",
    "sanity-import": "sanity dataset import lib/sanity/data/production.tar.gz production",
    "sanity-export": "sanity dataset export production lib/sanity/data/production.tar.gz",
    "lint": "next lint"
  },
  "dependencies": {
    "@headlessui/react": "^1.7.13",
    "@heroicons/react": "^2.0.17",
    "@portabletext/react": "^2.0.2",
    "@sanity/code-input": "^4.1.0",
    "@sanity/icons": "^2.2.2",
    "@sanity/image-url": "^1.0.2",
    "@sanity/table": "^1.0.1",
    "@sanity/types": "^3.8.3",
    "@sanity/ui": "^1.3.1",
    "@sanity/vision": "^3.8.3",
    "@tailwindcss/typography": "^0.5.9",
    "@vercel/og": "^0.5.1",
    "@web3forms/react": "^1.1.3",
    "clsx": "^1.2.1",
    "date-fns": "^2.29.3",
    "get-video-id": "^3.6.5",
    "next": "^13.4.12",
    "next-sanity": "^5.1.1",
    "next-seo": "^5.15.0",
    "next-sitemap": "^4.0.6",
    "next-themes": "^0.2.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-hook-form": "^7.43.9",
    "react-iframe": "^1.8.5",
    "react-refractor": "^2.1.7",
    "sanity": "^3.9.0",
    "sanity-plugin-asset-source-unsplash": "^1.0.6",
    "styled-components": "^5.3.9",
    "swr": "^2.1.2",
    "typescript": "^5.0.4"
  },
  "devDependencies": {
    "autoprefixer": "^10.4.14",
    "eslint": "^8.38.0",
    "eslint-config-next": "^13.3.0",
    "eslint-config-sanity": "^6.0.0",
    "postcss": "^8.4.21",
    "prettier": "^2.8.7",
    "prettier-plugin-tailwindcss": "^0.2.7",
    "sharp": "^0.32.0",
    "tailwindcss": "^3.3.1"
  }
}
```

**Additional context**

This issue only appears on Vercel build. I test on local build with `pnpm run build` and it passes. I've spent 3 days to look around but couldn't find a resolution

**Comment by stipsan** [comment]
Hi, you need to update `next-sanity` to get the latest typings used in the README :)
