### ISSUE TITLE
Desk crashes with Uncaught Error: Workspace: missing context value

### ISSUE THREAD

**Issue by ilyagru** [sanity-io/next-sanity#724]
**Describe the bug**

When embedding the studio into a Next.js app, the desk tool crashes and throws an error "Uncaught Error: Workspace: missing context value". What's interesting is that I have 2 identical projects and one of them works fine, the other crashes with the mentioned error. If I build the studio separately and go to localhost:3333/studio, it doesn't crash.

What could be the issue?

**To Reproduce**

sanity.config.ts
```ts
import { defineConfig, isDev } from 'sanity'
import { deskTool } from 'sanity/desk'
import { visionTool } from '@sanity/vision'
import { schemaTypes } from './src/schemas'

export default defineConfig({
  name: 'default',
  title: 'app-studio',
  projectId: '...',
  dataset: 'production',
  basePath: '/studio',
  plugins: [
    deskTool(),
    ...(isDev
      ? [
          visionTool({
            defaultApiVersion: 'v2023-11-02',
            defaultDataset: 'production'
          })
        ]
      : [])
  ],
  schema: {
    types: schemaTypes
  }
})
```

**Expected behavior**

No error is thrown.

**Screenshots**

<img width="1357" alt="Screenshot 2023-11-02 at 11 34 31" src="https://github.com/sanity-io/next-sanity/assets/18074511/c7ded0d9-1517-4f78-9e16-fbf853be1cd5">
<img width="1346" alt="Screenshot 2023-11-02 at 11 33 36" src="https://github.com/sanity-io/next-sanity/assets/18074511/7e67dc98-cadf-4c70-a95a-9d3d2e553a2c">
<img width="1380" alt="Screenshot 2023-11-02 at 11 34 17" src="https://github.com/sanity-io/next-sanity/assets/18074511/f768da64-4136-4e13-b60b-fbaa28b60d64">

**Which versions of Sanity are you using?**

Sanity v3.19.0
Next.js both v13.5.5 and v14.0.1

**What operating system are you using?**

macOS 14.1

**Which versions of Node.js / npm are you running?**

Run `npm -v && node -v` in the terminal and copy-paste the result here.

Node.js v18.18.2
pnpm v8.10.0

**Additional context**

**Security issue?**

Any security issues should be submitted directly to [security@sanity.io](mailto:security@sanity.io). In order to determine whether you are dealing with a security issue, ask yourself these two questions:

- Can I access something that's not mine, or something I shouldn't have access to?
- Can I disable something for other people? If the answer to either of those two questions are "yes", then you're probably dealing with a security issue. Note that even if you answer "no" to both questions, you may still be dealing with a security issue, so if you're unsure, just email us at [security@sanity.io](mailto:security@sanity.io.

**Comment by Steffi3rd** [comment]
Same problem

**Comment by oblodev** [comment]
Got the same problem. Same node version: 
![image](https://github.com/sanity-io/next-sanity/assets/22012778/c1fe50a1-b312-45b3-9d73-53ee346b44b1)

**Comment by jessetan** [comment]
I'm hitting this issue as well when trying to create a custom nav bar using the instructions at https://www.sanity.io/docs/studio-components-reference#db9fc60782a3

npm v10.2.3
Node v21.2.0

**Comment by manimul** [comment]
I just had this issue happening quite randomly on a Remix project with an embedded Studio.  No work was being done on the Sanity schemas or setup when it started happening. It would crash when i went to add new content on a Sanity document. 
I was able to get around it by opening the local Studio in a new browser on Incognito mode, and logging in again to Sanity, So perhaps it's some caching issue?

**Comment by federicocappellotto97** [comment]
Same here
```
"next": "14.0.4",
"next-sanity": "^7.0.10",
"@sanity/vision": "^3.24.1",
"sanity": "^3.24.1"
```
Worked before updating, now i get `Error: Workspace: missing context value`

**Comment by Vinam09** [comment]
Running into the same issue with my project, Has anyone found a workaround?

**Comment by abdealisaria** [comment]
Same error: missing context value.
My local sanity studio works fine using npm run dev
When I use sanity deploy that studio throws the same error.
![image](https://github.com/sanity-io/next-sanity/assets/45766822/9bb3f258-7b08-4b1d-80e4-d6a57c53e524)

**Comment by fostimus** [comment]
Same here

**Comment by alexanderkalachev** [comment]
After latest updates, same issue is surfaced when hosting on Vercel, but locally all works fine. Frustrating, because absolutely not clear how to fix it.

**Comment by alexanderkalachev** [comment]
Is there any progress on this issue? I've tried many different approaches to find what causes that, but couldn't find it.

**Comment by notflip** [comment]
I've encountered this issue as well, after adding a plugin to Sanity.

**Comment by Kakha01** [comment]
I fixed this issue by

1. deleting `node_modules` folder in my project directory
2. clearing pnpm cache with `pnpm store prune` in terminal
3. and reinstalling packages with `pnpm install`

**Comment by stipsan** [comment]
Newer `sanity` versions now detect this problem and throws an error that send you to our new docs for how to mitigate: https://www.sanity.io/help/missing-context-error
