### ISSUE TITLE
NextStudio scheme prop not working for data-ui="Navbar" component

### ISSUE THREAD

**Issue by LinnJS** [sanity-io/next-sanity#737]
**Describe the bug**

When switching the NextStudio scheme to "light" the studio properly reflects the light theme besides the data-ui="Navbar" component. 

**To Reproduce**

1. Create a new NextJS project use app router
2. Init the project with Sanity v3 and select embed option with app router
3. Add scheme prop to NextStudio in `src/studio/[[...index]]/page.tsx` set to light
4. Set browser to dark mode
5. See Navbar is stuck on system setting rather than using the light setting coming from NextStudio scheme prop.

**Expected behavior**

When browser is in dark mode and scheme prop is set to light mode the scheme prop should override the system default setting.

**Screenshots**
![Screenshot 2023-11-12 at 6 18 25 PM](https://github.com/sanity-io/next-sanity/assets/23741323/0c00908b-911b-476f-8fd4-53b6c0e23e3d)

**Which versions of Sanity are you using?**

➜ sanity versions
@sanity/cli (global)  3.19.2 (up to date)
@sanity/image-url      1.0.2 (up to date)
@sanity/vision        3.19.2 (up to date)
sanity                3.19.2 (up to date)

**What operating system are you using?**

MacOS 14.1.1 (23B81) using a Chromium browser

**Which versions of Node.js / npm are you running?**

➜ npm -v && node -v
9.3.1
v18.14.0

**Comment by stipsan** [comment]
Verified as fixed in `sanity` version `3.28.0` 🙌
