### ISSUE TITLE
Cannot get final name for export 'Observable' of __barrel_optimize__

### ISSUE THREAD

**Issue by endosama** [sanity-io/next-sanity#797]
**Describe the bug**

I've started experiencing these issues after adding Sanity to my Next.js/Typescript app.
```
Cannot get final name for export 'Observable' of __barrel_optimize__?names=Observable,lastValueFrom!=!./node_modules/rxjs/dist/esm5/index.js
```
This is probably related to some issue with Next.js `optimizePackageImports` feature and the way the imports are done in the `@sanity/client` package.

Similar issue here: https://github.com/vercel/next.js/issues/55818

Is there any known workaround to solve this? Thanks

**To Reproduce**

Add sanity to an existing next project. Run `yarn build`

**Expected behavior**

The build should be successful

**Which versions of Sanity are you using?**

```
"@sanity/client": "^6.4.9",
"next-sanity": "5.5.10",
```
also tried 
```
"@sanity/client": "^6.9.1",
"next-sanity": "^7.0.1",
```
But I've also tried a few older versions
**What operating system are you using?**
```
Platform: darwin
Arch: arm64
```

**Which versions of Node.js / npm are you running?**
```
Node: 20.10.0
yarn: 1.22.19
```
tried with both next `14.0.3` and `^13.4.19`

**Comment by dennis-pushh** [comment]
I have the same issue when setting up a monorepo with turborepo. Any updates?

**Comment by stipsan** [comment]
> I have the same issue when setting up a monorepo with turborepo. Any updates?

No, we haven't seen this issue on internal projects or been able to reproduce.
I recommend reporting it at [Vercel](https://github.com/vercel/next.js/issues/new?assignees=&labels=template%3A+bug&projects=&template=1.bug_report.yml) and submit a reproduction case with it 🙂
