### ISSUE TITLE
Exclude document types from dataset streamed to browser

### ISSUE THREAD

**Issue by heggemsnes** [sanity-io/next-sanity#80]
Hi!

We use the usePreviewSubscription a lot, but as we use Sanity more and more we have document types that doesn't really need preview. Example is like a "comment" document type. Removing these would make the dataset much lighter as these document types are several thousand but the "previewable" documents are usually a lot fewer.

I understand that this would mean that this content could not be shown in the preview at all.

**Comment by kmelve** [comment]
Hi! We're looking into this, but it's “not that simple.” First and foremost, we have to figure out what should happen if you reference a document that aren't available (https://github.com/sanity-io/groq-store/pull/2)

**Comment by stipsan** [comment]
Hi, this is now possible in [`v1.1.0`](https://github.com/sanity-io/next-sanity/releases/tag/v1.1.0) by using the [`includeTypes`](https://github.com/sanity-io/next-sanity#usage:~:text=local%20groq%2Dstore.-,includeTypes,-%3A%20%5B%27page) option 😄
