### ISSUE TITLE
Fix Migration Guides' links 

### ISSUE THREAD

**Issue by rubenprodev** [sanity-io/next-sanity#841]
I wanted to check the migration guide from v4 to v5 but when you [reach it](https://github.com/sanity-io/next-sanity/?tab=readme-ov-file#migration-guides) there are two options:

- **app-router** links to https://github.com/sanity-io/next-sanity/blob/main/MIGRATE-v4-to-v5-pages-app-router.md and should link to https://github.com/sanity-io/next-sanity/blob/main/MIGRATE-v4-to-v5-app-router.md instead
- **pages-router** links to https://github.com/sanity-io/next-sanity/blob/main/MIGRATE-v4-to-v5-pages-pages-router.md and should link to https://github.com/sanity-io/next-sanity/blob/main/MIGRATE-v4-to-v5-pages-router.md instead

I would've fixed by myself via PR, but already have a project with the same name and now I'm too lazy and busy to do it. Hope you don't mind, but wanted to reflect it to help others on my same situation. You could get those links just clicking on the other ones and looking for these ones, but just in case 😉

**Comment by stipsan** [comment]
Thanks @rubenprodev, fixed!
@Tobeyforce we hear you, projects vary a lot in implementation details and what features they're using. We're exploring ways to account for this and find the right balance. For now I recommend using the [Personal Website](https://github.com/sanity-io/template-nextjs-personal-website) template as a reference implementation as it demonstrates how to use all the Next features (Webhooks, `revalidateTag`, Draft Mode) and Sanity features (Embedded Studio, Presentation Tool, Visual Editing).
You can also open issues and ask us for guidance on how to migrate specific features from v4 to v7, adapted to your use case and the functionality you wish to have 😄
