### ISSUE TITLE
useCdn warning even after setting it to false

### ISSUE THREAD

**Issue by AbhinavGS** [sanity-io/next-sanity#844]
I have set useCdn to false still I'm getting 
"Since you haven't set a value for `useCdn`, we will deliver content using our global, edge-cached API-CDN. If you wish to have content delivered faster, set `useCdn: false` to use the Live API. Note: You may incur higher costs using the live API"
warning in terminal when I run the app
Also content is not getting updated

```
export const client = createClient({
  apiVersion,
  dataset,
  projectId,
  useCdn: false,
});
```

**Comment by stipsan** [comment]
Hi @AbhinavGS,

Can you provide a codesandbox link, or a github repo link, were we can see this happen?
