### ISSUE TITLE
Next.js 14: Data Not Updating Despite Changes, Tried Revalidation and 'no-store' Caching

### ISSUE THREAD

**Issue by Muhammad-Hashim** [sanity-io/next-sanity#879]
Hello, I'm using the latest version of Next.js (version 14), and I'm facing an issue where the data doesn't refresh when I make changes on the live website. Strangely, when I modify the data locally, the changes are reflected. I've attempted to address this by setting revalidation: 1, but unfortunately, it hasn't had any effect. Additionally, I've set caching to 'no-store'. Am I overlooking something? Please provide guidance on resolving this issue.
  
![image](https://github.com/sanity-io/next-sanity/assets/52486100/1f3abdff-096b-40f3-a733-9cd7bb09a41c)

**Comment by stipsan** [comment]
Could you share your `createClient` configuration, as well as what version of Sanity packages you're on?

**Comment by stipsan** [comment]
The fix is to pass in the `cache` as the third argument to `client.fetch`, instead of the second argument:
```diff
-const posts = await client.fetch<Post[]>(`*[_type == "post"]`, {cache: 'no-store'})
+const posts = await client.fetch<Post[]>(`*[_type == "post"]`, {}, {cache: 'no-store'})
```
