### ISSUE TITLE
ZeroWidthSpace in text

### ISSUE THREAD

**Issue by rodzerjohn** [sanity-io/next-sanity#984]
Hello,

I've encountered a strange bug where every text retrieved from a Groq query in Sanity CMS contains zero-width spaces. What could be causing this issue?

Thanks in advance!

<img width="1256" alt="image" src="https://github.com/sanity-io/next-sanity/assets/49143840/6be96c92-37ec-4e6f-ada5-6f49d40f9b7e">

**Comment by stipsan** [comment]
Hi, this is how stega is implemented, for integrating with Vercel Visual Editing and Sanity Presentation.
Somewhere in your code you probably have a client configuration like this:
```ts
import {createClient} from '@sanity/client'

const client = createClient({
  // ... other options
  stega: {
    enabled: true, // <- this is what adds the hidden characters
    studioUrl: '/studio'
  }
})
```

**Comment by rodzerjohn** [comment]
> Hi, this is how stega is implemented, for integrating with Vercel Visual Editing and Sanity Presentation. Somewhere in your code you probably have a client configuration like this:
> 
> ```ts
> import {createClient} from '@sanity/client'
> 
> const client = createClient({
>   // ... other options
>   stega: {
>     enabled: true, // <- this is what adds the hidden characters
>     studioUrl: '/studio'
>   }
> })
> ```

Thank you
